packages:
  - packages/*
  - examples/sveltekit

autoInstallPeers: false

packageExtensions:
  "@sveltejs/package@2.5.8":
    peerDependencies:
      typescript: "^5.0.0 || ^6.0.0"

overrides:
  vite: 8.2.2
  "@sveltejs/kit>cookie": ^0.7.2
  sharp: 0.35.4

allowBuilds:
  core-js: false

minimumReleaseAgeExclude:
  - "@posthog/types@1.407.0"
  - "@types/node@26.4.0"
  - posthog-js@1.421.0
