export interface SchemaEvent {
  params?: Record<string, string>;
}

export interface Schema {
  events: Record<string, SchemaEvent>;
}

function snakeToPascal(s: string): string {
  return s
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function snakeToCamel(s: string): string {
  const pascal = snakeToPascal(s);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

export function generateTypes(schema: Schema): string {
  const eventNames = Object.keys(schema.events);
  const lines: string[] = ["// @generated by @alyt/codegen — do not edit manually", ""];

  lines.push(
    `export type AnalyticsEventName =\n\t| ${eventNames.map((n) => `"${n}"`).join("\n\t| ")};`,
  );
  lines.push("");
  lines.push("export interface AnalyticsEventMap {");
  for (const [name, def] of Object.entries(schema.events)) {
    const params = def?.params;
    if (params && Object.keys(params).length > 0) {
      const fields = Object.entries(params)
        .map(([k, v]) => `${k}: ${v}`)
        .join("; ");
      lines.push(`\t${name}: { ${fields} };`);
    } else {
      lines.push(`\t${name}: Record<string, never>;`);
    }
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export function generateTracker(schema: Schema): string {
  const lines: string[] = [
    "// @generated by @alyt/codegen — do not edit manually",
    'import type { AnalyticsClient, TrackOptions } from "@alyt/core";',
    "",
    "export function createTracker(client: AnalyticsClient) {",
    "\treturn {",
  ];

  const entries = Object.entries(schema.events);
  for (let i = 0; i < entries.length; i++) {
    const [name, def] = entries[i];
    const methodName = snakeToCamel(name);
    const params = def?.params;

    if (params && Object.keys(params).length > 0) {
      const paramEntries = Object.entries(params);
      const args = paramEntries.map(([k, v]) => `${snakeToCamel(k)}: ${v}`).join(", ");
      const obj = paramEntries.map(([k]) => `${k}: ${snakeToCamel(k)}`).join(", ");
      lines.push(`\t\t${methodName}(${args}, options?: TrackOptions) {`);
      lines.push(`\t\t\tclient.track("${name}", { ${obj} }, options);`);
      lines.push("\t\t},");
    } else {
      lines.push(`\t\t${methodName}(options?: TrackOptions) {`);
      lines.push(`\t\t\tclient.track("${name}", undefined, options);`);
      lines.push("\t\t},");
    }
  }

  lines.push("\t};");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
